### ISSUE TITLE
Fatal Error: ClassConstantReferenceImpl cannot be cast to StringLiteralExpression

### ISSUE THREAD

**Issue by CarsonF** [Sorien/silex-idea-plugin#29]
```
com.jetbrains.php.lang.psi.elements.impl.ClassConstantReferenceImpl cannot be cast to com.jetbrains.php.lang.psi.elements.StringLiteralExpression
java.lang.ClassCastException: com.jetbrains.php.lang.psi.elements.impl.ClassConstantReferenceImpl cannot be cast to com.jetbrains.php.lang.psi.elements.StringLiteralExpression
    at sk.sorien.silexplugin.pimple.PimplePhpTypeProvider.getTypeForParameterOfAnonymousFunction(PimplePhpTypeProvider.java:167)
    at sk.sorien.silexplugin.pimple.PimplePhpTypeProvider.getType(PimplePhpTypeProvider.java:35)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:43)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:37)
    at com.intellij.openapi.util.Computable$NotNullCachedComputable.compute(Computable.java:52)
    at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
    at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getType(PhpTypeInfo.java:37)
    at com.jetbrains.php.lang.psi.elements.impl.PhpTypedElementImpl.getType(PhpTypedElementImpl.java:26)
    at com.jetbrains.php.lang.psi.elements.impl.FunctionImpl.visitReturn(FunctionImpl.java:175)
    at com.jetbrains.php.lang.psi.elements.impl.FunctionImpl.scanTree(FunctionImpl.java:208)
    at com.jetbrains.php.lang.psi.elements.impl.FunctionImpl.getLocalType(FunctionImpl.java:152)
    at com.jetbrains.php.lang.psi.stubs.PhpFunctionElementType.createStub(PhpFunctionElementType.java:30)
    at com.jetbrains.php.lang.psi.stubs.PhpFunctionElementType.createStub(PhpFunctionElementType.java:20)
    at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTreeFor(DefaultStubBuilder.java:60)
    at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTree(DefaultStubBuilder.java:36)
    at com.intellij.psi.impl.source.PsiFileImpl.calcStubTree(PsiFileImpl.java:997)
    at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:62)
    at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:39)
    at com.intellij.psi.stubs.StubIndexImpl$2.perform(StubIndexImpl.java:274)
    at com.intellij.psi.stubs.StubIndexImpl$2.perform(StubIndexImpl.java:265)
    at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:81)
    at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:265)
    at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:238)
    at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:76)
    at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:95)
    at com.intellij.psi.stubs.StubIndexImpl.get(StubIndexImpl.java:227)
    at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:144)
    at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:134)
    at com.jetbrains.php.PhpIndexImpl.getClassesByNameInScope(PhpIndexImpl.java:217)
    at com.jetbrains.php.PhpIndexImpl.getClassesByName(PhpIndexImpl.java:211)
    at com.jetbrains.php.completion.PhpCompletionContributor$PhpClassRefCompletionProvider.addCompletions(PhpCompletionContributor.java:453)
    at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
    at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
    at com.jetbrains.php.completion.PhpCompletionContributor.fillCompletionVariants(PhpCompletionContributor.java:303)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:135)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:128)
    at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:90)
    at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
    at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
    at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:112)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator.a(CompletionProgressIndicator.java:796)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$1000(CompletionProgressIndicator.java:90)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:778)
    at com.intellij.codeInsight.completion.AsyncCompletion$1$1$1.run(CompletionThreading.java:93)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:872)
    at com.intellij.codeInsight.completion.AsyncCompletion$1$1.run(CompletionThreading.java:88)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
    at com.intellij.codeInsight.completion.AsyncCompletion$1.run(CompletionThreading.java:84)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:695)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

**Comment by Sorien** [comment]
i pushed commit to prevent this ... could you try last master version if its fixed or not

**Comment by CarsonF** [comment]
Yeah just installed it, I'll see if it comes up again today

**Comment by Sorien** [comment]
if you find something broken just let me know otherwise i'll release 0.9.8 tomorrow

**Comment by CarsonF** [comment]
Yeah I haven't seen anything, thanks!
